feat: add plugin-register;
dotbitHQ/dotbit.js pull request #34
Opened 2022-12-26 10:16 UTC by web3max

2022-12-26 14:56 UTC, zgayjjf requested changes

2022-12-26 14:56 UTC, zgayjjf commented on README.md
> +- [@dotbit/plugin-register](./packages/plugin-register/README.md): A plugin for register .bit account.
"A plugin to register .bit account" or "A plugin for registering .bit account."

2022-12-26 14:56 UTC, zgayjjf commented on src/const.ts
> +  notOpenRegister= -1,
It would be great to place a link to the source in backend.

2022-12-26 14:56 UTC, zgayjjf commented on src/const.ts
> +// ID of the payment method, source: https://register-api.did.id/v1/token/list
404, add a POST method.

2022-12-26 14:56 UTC, zgayjjf commented on src/tools/common.ts
> +export function computedEvmChainTypeByCoinType (coinType: CoinType): ChainType {
Maybe 'compute' is better than `computed`

2022-12-26 14:56 UTC, zgayjjf commented on packages/plugin-register/src/index.ts
> +      await this.bitBuilder.returnTrxHashToService({
A `register_result` or something like that should be returned to developers so they can query the registration progress.

2022-12-26 14:59 UTC, zgayjjf commented
The `README` should be detailed, clarifying the requirement and other info about each registration method.

2022-12-27 02:24 UTC, mozwell commented on packages/plugin-register/tests/index.test.ts
> +    await account.register({
We should have a return value of 'register' API and then check the return value in Unit Test

2022-12-28 12:12 UTC, zgayjjf approved these changes

2022-12-29 08:28 UTC, merged