fix: Mint sub-account bug;
dotbitHQ/dotbit.js pull request #4
Opened 2022-08-12 06:55 UTC by web3max

2022-08-12 08:52 UTC, zgayjjf requested changes

2022-08-12 08:52 UTC, zgayjjf commented on src/BitAccount.ts
> +  keyInfo?: KeyInfo,
Add the description that the `keyInfo` have higher priority over `mintForAccount`, and put them together, rather than isolated by `registerYears`

2022-08-12 08:52 UTC, zgayjjf commented on src/const.ts
> +export enum CHAR_TYPE {
Add a reference here: https://github.com/dotbitHQ/das-types/blob/master/rust/src/constants.rs#L145
(Single Source of Truth principle)

2022-08-12 08:52 UTC, zgayjjf commented on src/fetchers/BitIndexer.type.ts
> +  key_info?: KeyInfo,
`key_info` is necessary

2022-08-12 08:52 UTC, zgayjjf commented on src/fetchers/SubAccountAPI.ts
> +  mint_for_account?: string,
It is better to modify here instead of modify `BitKeyInfo`

2022-08-12 08:52 UTC, zgayjjf commented on src/tools/account.ts
> +  const split = splitter.splitGraphemes(account)
Maybe it would be better to use graphemes rather than split, which is a verb.

2022-08-12 08:52 UTC, zgayjjf commented on src/tools/account.ts
> +  const koreanNotKnownChar = koreanSplitArr.find((item: ICharInfo) => {
The codes here are mostly copy-pasted, it would be better to reduce the duplicated codes, saving the future effort of adding new charsets.

2022-08-12 11:02 UTC, web3max commented on src/tools/account.ts
> +  const koreanNotKnownChar = koreanSplitArr.find((item: ICharInfo) => {
This has plans to rewrite it, and will be updated together afterwards.

2022-08-15 07:10 UTC, zgayjjf approved these changes

2022-08-15 07:13 UTC, merged